export const objectsData = [
  {
    name: "2-комнатная квартира",
    address: "Москва, ул. Маяковского, д.5, кв.125. Хотя скорее всего будет две строки или три даже",
    debtValue: 99875.89,
    notifications: {
      chat: 100,
      map: 10,
      general: 7,
    },
    buildingYear: 1147,
    overhaulYear: 1780,
    floorsNumber: 40,
    apartmentsNumber: 800,
    payments: [
      {
        purpose: "ТСЖ № 63545-86-99",
        plan: 100,
        fact: 100,
        receipt: "pretend this is an url",
        payLink: "pretend this is an URL too maybe?",
      },
      {
        purpose: "Электроэнергия № 4578952-22",
        plan: 10,
        fact: 10,
        receipt: "pretend this is an url",
        payLink: "pretend this is an URL too maybe?",
      },
      {
        purpose: "МТС № 4578952-22",
        plan: 5,
        fact: 5,
        receipt: "pretend this is an url",
        payLink: "pretend this is an URL too maybe?",
      },
    ],
  },
  {
    name: "Однушка 7 м в Капотне",
    address: "Москва, ул. Другая, д.5, кв.125. Хотя скорее всего будет две строки или три даже",
    debtValue: 0,
    notifications: {
      chat: 3,
      map: 11,
      general: 7,
    },
    buildingYear: 1347,
    overhaulYear: 1980,
    floorsNumber: 400,
    apartmentsNumber: 8000,
    payments: [
      {
        purpose: "ТСЖ № 63545-863456-99",
        plan: 100,
        fact: 150,
        receipt: "pretend this is an url",
        payLink: "pretend this is an URL too maybe?",
      },
      {
        purpose: "Электроэнергия № 45789342552-22",
        plan: 7,
        fact: 7,
        receipt: "pretend this is an url",
        payLink: "pretend this is an URL too maybe?",
      },
      {
        purpose: "МТС № 45782342341952-22",
        plan: 9,
        fact: 9,
        receipt: "pretend this is an url",
        payLink: "pretend this is an URL too maybe?",
      },
    ],
  },
];

export const objectList = ["Москва, ул. Маяковского, д. 5, кв. 125", "Москва, ул. Другая, д. 5, кв. 125"];

export const servicesList = [
  "Показать все",
  "Сантехнические работы",
  "Электромонтажные работы",
  "Клининг",
  "Установка окон",
  "Вывоз муссора",
  "Услуги грузчиков",
  "Мастер на час",
  "Услуги няни",
  "Домработница",
];

export const portfolio = [
  "/img/image 1843.png",
  "/img/image 1844.png",
  "/img/image 1845.png",
  "/img/image 1846.png",
  "/img/image 1847.png",
  "/img/image 1848.png",
  "/img/image 1849.png",
];

export const mastersData = [
  {
    profilePic: "/img/temp/adProfilePic.png",
    name: "Константин Константинопольский",
    isPaidAd: false,
    location: "Москва, Метро Сокол",
    price: "По договоренности",
    description:
      "Выполню любой спектр сантехнических услуг: отопление, водоотведение, канализация, установка сантехнического оборудования. Работаю в Москве и ближайшем Подмосковье по предварительной записи. Оплата работы по предварительной согласованностью и прочие формальности тоже соблюдены",
    sliderPhotos: [
      "/img/temp/image 1843.png",
      "/img/temp/image 1844.png",
      "/img/temp/image 1845.png",
      "/img/temp/image 1846.png",
      "/img/temp/image 1847.png",
      "/img/temp/image 1848.png",
      "/img/temp/image 1849.png",
    ],
    phone: 123456,
    rating: 3.5,
    votes: 100,
    documentChecked: true,
    contract: true,
  },
  {
    profilePic: "/img/temp/image 1842.png",
    name: "Александр Метропольский",
    isPaidAd: true,
    location: "Москва, Метро Новогиреево",
    price: "1000",
    description:
      "Выполню любой спектр сантехнических услуг: отопление, водоотведение, канализация, установка сантехнического оборудования. Работаю в Москве и ближайшем Подмосковье по предварительной записи. ",
    sliderPhotos: [
      "/img/temp/image 1843.png",
      "/img/temp/image 1844.png",
      "/img/temp/image 1845.png",
      "/img/temp/image 1846.png",
      "/img/temp/image 1847.png",
    ],
    phone: 123456,
    rating: 3.5,
    votes: 100,
    documentChecked: true,
    contract: false,
  },
  {
    profilePic: "/img/temp/image 1886.png",
    name: "Компания «Водяной»",
    isPaidAd: true,
    location: "Москва, Метро Новогиреево",
    price: "от 1000",
    description: "Установка сантехники • Устранение засоров • Копание колодцев • Водоотведение • Бурение скважин • Установка кондиционеров",
    sliderPhotos: [
      "/img/temp/image 1843.png",
      "/img/temp/image 1844.png",
      "/img/temp/image 1845.png",
      "/img/temp/image 1846.png",
      "/img/temp/image 1847.png",
      "/img/temp/image 1844.png",
      "/img/temp/image 1845.png",
      "/img/temp/image 1846.png",
      "/img/temp/image 1847.png",
    ],
    phone: 12343456,
    rating: 0,
    votes: 0,
    documentChecked: false,
    contract: true,
  },
];
